[package]
name = "trip-analyzer"
version = "1.0.0"
authors = ["Shell Script Magazine <shellmag@example.com>"]
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "2.33"
csv = "1.1"
hdrhistogram = "6.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
