[package]
name = "otenki-09"
version = "0.9.0"
authors = ["Shell Script Magazine <shellmag@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9"
