[package]
name = "otenki-010"
version = "0.10.0"
authors = ["Shell Script Magazine <shellmag@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.10", features = ["blocking"] }
